name: Simud IPTV Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run scraper
        run: ./gradlew :scraper:run
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Simud-IPTV
          path: Simud.m3u
