name: Marvel IPTV Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install cloudscraper
        run: npm install cloudscraper

      - name: Fetch archive page
        run: node -e "const cloudscraper = require('cloudscraper'); cloudscraper.get('https://streamingunity.to/archive').then(html => require('fs').writeFileSync('archive.html', html)).catch(err => { console.error('Errore cloudscraper:', err); process.exit(1); });"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run scraper
        run: ./gradlew :scraper:run --stacktrace

      - name: Commit and push updated M3U file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Simud.m3u
          git commit -m "Aggiornato file M3U con nuovi flussi Marvel" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true

      - name: Upload M3U and debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Simud-IPTV-Debug
          path: |
            Simud.m3u
            response.html
            initial_response.html
            archive.html
        continue-on-error: true
